#!/bin/bash
# Polymarket continuous scheduler — isolated from A-share automation

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

load_env_defaults() {
    local env_file="$1"
    local line key value
    [ -f "$env_file" ] || return 0

    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            ''|\#*) continue ;;
        esac
        key="${line%%=*}"
        value="${line#*=}"
        if [ -z "${!key+x}" ]; then
            eval "export ${key}=${value}"
        fi
    done < "$env_file"
}

load_env_defaults "$PROJECT_DIR/.env"

: "${DATA_DIR:=$HOME/quantpilot_data}"
: "${POLY_DATA_DIR:=$DATA_DIR/polymarket}"
: "${POLY_PAPER_ONLY:=true}"
: "${POLY_ENABLE_SPLIT_SELL:=false}"
: "${POLY_ENABLE_TOP_TRADER_MIRROR:=false}"
: "${POLY_SCAN_INTERVAL_SECONDS:=300}"
: "${POLY_CATALOG_REFRESH_SECONDS:=900}"
: "${POLY_CATALOG_REFRESH_JOB_SECONDS:=1800}"
: "${POLY_MIN_NET_EDGE:=0.01}"
: "${POLY_DEFAULT_GAS_COST:=0}"
: "${POLY_SLIPPAGE_BUFFER:=0.005}"
: "${POLY_TARGET_NOTIONAL_PER_OPP:=25}"
: "${POLY_MAX_ACTIVE_MARKETS:=250}"
: "${POLY_MIN_DEPTH_EDGE_PER_SHARE:=0}"
: "${POLY_MARKET_COOLDOWN_SECONDS:=60}"
: "${POLY_LOCAL_BOOK_DEPLETION_TTL_SECONDS:=900}"
: "${POLY_MAX_MARKET_NOTIONAL_PER_DAY:=50}"
: "${POLY_MAX_DAILY_NOTIONAL:=250}"
: "${POLY_MAX_DAILY_LOSS:=25}"
: "${POLY_CATALOG_PAGE_SIZE:=1000}"
: "${POLY_CATALOG_FETCH_WORKERS:=4}"
: "${POLY_CATALOG_FETCH_FEE_RATES:=true}"
: "${POLY_BOOK_SOURCE:=http}"
: "${POLY_BOOK_FETCH_USE_BATCH:=true}"
: "${POLY_BOOK_FETCH_BATCH_SIZE:=500}"
: "${POLY_BOOK_FETCH_WORKERS:=8}"
: "${POLY_WS_MARKET_URL:=wss://ws-subscriptions-clob.polymarket.com/ws/market}"
: "${POLY_WS_HEARTBEAT_SECONDS:=10}"
: "${POLY_WS_RECONNECT_MIN_SECONDS:=1}"
: "${POLY_WS_RECONNECT_MAX_SECONDS:=30}"
: "${POLY_WS_READY_TIMEOUT_SECONDS:=15}"
: "${POLY_WS_MIN_READY_RATIO:=0.95}"
: "${POLY_WS_SUBSCRIBE_BATCH_SIZE:=500}"
: "${POLY_WS_RECONCILE_ENABLED:=false}"
: "${POLY_WS_RECONCILE_SECONDS:=10}"
: "${POLY_WS_RECONCILE_TIMEOUT_SECONDS:=3}"
: "${POLY_WS_RECONCILE_BATCH_SIZE:=50}"
: "${POLY_WS_RECONCILE_WORKERS:=4}"
: "${POLY_WS_RECONCILE_MAX_TOKENS_PER_CYCLE:=500}"
: "${POLY_DIRTY_SCAN_ENABLED:=false}"
: "${POLY_DIRTY_SCAN_INTERVAL_SECONDS:=0.1}"
: "${POLY_STORAGE_ASYNC_FLUSH_ENABLED:=false}"
: "${POLY_STORAGE_ASYNC_FLUSH_SECONDS:=1}"
: "${POLY_BOOK_TOP_SAMPLE_SECONDS:=0}"
: "${POLY_BOOK_TOP_RETENTION_HOURS:=72}"
: "${POLY_BOOK_TOP_RETENTION_JOB_SECONDS:=3600}"
PYTHON_BIN="$PROJECT_DIR/.venv/bin/python"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
export DATA_DIR POLY_DATA_DIR POLY_PAPER_ONLY POLY_ENABLE_SPLIT_SELL POLY_ENABLE_TOP_TRADER_MIRROR
export POLY_SCAN_INTERVAL_SECONDS POLY_CATALOG_REFRESH_SECONDS POLY_CATALOG_REFRESH_JOB_SECONDS
export POLY_MIN_NET_EDGE POLY_DEFAULT_GAS_COST POLY_SLIPPAGE_BUFFER POLY_TARGET_NOTIONAL_PER_OPP
export POLY_MIN_DEPTH_EDGE_PER_SHARE POLY_MARKET_COOLDOWN_SECONDS POLY_LOCAL_BOOK_DEPLETION_TTL_SECONDS
export POLY_MAX_MARKET_NOTIONAL_PER_DAY POLY_MAX_DAILY_NOTIONAL POLY_MAX_DAILY_LOSS
export POLY_MAX_ACTIVE_MARKETS POLY_CATALOG_PAGE_SIZE POLY_CATALOG_FETCH_WORKERS POLY_CATALOG_FETCH_FEE_RATES
export POLY_BOOK_SOURCE POLY_BOOK_FETCH_USE_BATCH POLY_BOOK_FETCH_BATCH_SIZE POLY_BOOK_FETCH_WORKERS
export POLY_WS_MARKET_URL POLY_WS_HEARTBEAT_SECONDS POLY_WS_RECONNECT_MIN_SECONDS POLY_WS_RECONNECT_MAX_SECONDS
export POLY_WS_READY_TIMEOUT_SECONDS POLY_WS_MIN_READY_RATIO POLY_WS_SUBSCRIBE_BATCH_SIZE
export POLY_WS_RECONCILE_ENABLED POLY_WS_RECONCILE_SECONDS POLY_WS_RECONCILE_TIMEOUT_SECONDS
export POLY_WS_RECONCILE_BATCH_SIZE POLY_WS_RECONCILE_WORKERS
export POLY_WS_RECONCILE_MAX_TOKENS_PER_CYCLE
export POLY_DIRTY_SCAN_ENABLED POLY_DIRTY_SCAN_INTERVAL_SECONDS
export POLY_STORAGE_ASYNC_FLUSH_ENABLED POLY_STORAGE_ASYNC_FLUSH_SECONDS
export POLY_BOOK_TOP_SAMPLE_SECONDS
export POLY_BOOK_TOP_RETENTION_HOURS POLY_BOOK_TOP_RETENTION_JOB_SECONDS
export PYTHON_BIN PYTHONPATH

mkdir -p "$PROJECT_DIR/logs"
cd "$PROJECT_DIR"
source .venv/bin/activate

exec "$PYTHON_BIN" -m polymarket.scheduler
