#!/bin/bash
# QuantPilot US microstructure major-flow report.

set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

EXTERNAL_DATA_DIR="${DATA_DIR-}"
EXTERNAL_REPORT_DELIVERY_METHOD="${REPORT_DELIVERY_METHOD-}"
EXTERNAL_REPORT_TO="${REPORT_TO-}"
EXTERNAL_REPORT_FROM="${REPORT_FROM-}"
EXTERNAL_SMTP_HOST="${SMTP_HOST-}"
EXTERNAL_SMTP_PORT="${SMTP_PORT-}"
EXTERNAL_SMTP_USER="${SMTP_USER-}"
EXTERNAL_SMTP_PASSWORD="${SMTP_PASSWORD-}"
EXTERNAL_US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_DATE="${US_MICROSTRUCTURE_DATE-}"
EXTERNAL_US_MICROSTRUCTURE_REPORT_SYMBOLS="${US_MICROSTRUCTURE_REPORT_SYMBOLS-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_HOST="${US_MICROSTRUCTURE_NAS_HOST-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_DIR="${US_MICROSTRUCTURE_NAS_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_SEND_EMAIL="${US_MICROSTRUCTURE_SEND_EMAIL-}"
EXTERNAL_US_MICROSTRUCTURE_RUN_VALIDATION="${US_MICROSTRUCTURE_RUN_VALIDATION-}"
EXTERNAL_US_MICROSTRUCTURE_VALIDATION_END="${US_MICROSTRUCTURE_VALIDATION_END-}"
EXTERNAL_US_MICROSTRUCTURE_POST_REPORT_VALIDATION="${US_MICROSTRUCTURE_POST_REPORT_VALIDATION-}"
EXTERNAL_US_MICROSTRUCTURE_UPDATE_PRICES="${US_MICROSTRUCTURE_UPDATE_PRICES-}"
EXTERNAL_US_MICROSTRUCTURE_REPAIR_UPLOADS="${US_MICROSTRUCTURE_REPAIR_UPLOADS-}"
EXTERNAL_US_MICROSTRUCTURE_RUN_READINESS="${US_MICROSTRUCTURE_RUN_READINESS-}"
EXTERNAL_US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY="${US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY-}"
EXTERNAL_US_MICROSTRUCTURE_PRICE_CSV="${US_MICROSTRUCTURE_PRICE_CSV-}"
EXTERNAL_US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS="${US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS-}"
EXTERNAL_QLIB_DATA_DIR="${QLIB_DATA_DIR-}"

if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

if [ -f "$PROJECT_DIR/reporter/.env" ]; then
    set -a
    source "$PROJECT_DIR/reporter/.env"
    set +a
fi

[ -n "$EXTERNAL_DATA_DIR" ] && DATA_DIR="$EXTERNAL_DATA_DIR"
[ -n "$EXTERNAL_REPORT_DELIVERY_METHOD" ] && REPORT_DELIVERY_METHOD="$EXTERNAL_REPORT_DELIVERY_METHOD"
[ -n "$EXTERNAL_REPORT_TO" ] && REPORT_TO="$EXTERNAL_REPORT_TO"
[ -n "$EXTERNAL_REPORT_FROM" ] && REPORT_FROM="$EXTERNAL_REPORT_FROM"
[ -n "$EXTERNAL_SMTP_HOST" ] && SMTP_HOST="$EXTERNAL_SMTP_HOST"
[ -n "$EXTERNAL_SMTP_PORT" ] && SMTP_PORT="$EXTERNAL_SMTP_PORT"
[ -n "$EXTERNAL_SMTP_USER" ] && SMTP_USER="$EXTERNAL_SMTP_USER"
[ -n "$EXTERNAL_SMTP_PASSWORD" ] && SMTP_PASSWORD="$EXTERNAL_SMTP_PASSWORD"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_DIR" ] && US_MICROSTRUCTURE_DIR="$EXTERNAL_US_MICROSTRUCTURE_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_DATE" ] && US_MICROSTRUCTURE_DATE="$EXTERNAL_US_MICROSTRUCTURE_DATE"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_REPORT_SYMBOLS" ] && US_MICROSTRUCTURE_REPORT_SYMBOLS="$EXTERNAL_US_MICROSTRUCTURE_REPORT_SYMBOLS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_HOST" ] && US_MICROSTRUCTURE_NAS_HOST="$EXTERNAL_US_MICROSTRUCTURE_NAS_HOST"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_DIR" ] && US_MICROSTRUCTURE_NAS_DIR="$EXTERNAL_US_MICROSTRUCTURE_NAS_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_SEND_EMAIL" ] && US_MICROSTRUCTURE_SEND_EMAIL="$EXTERNAL_US_MICROSTRUCTURE_SEND_EMAIL"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_RUN_VALIDATION" ] && US_MICROSTRUCTURE_RUN_VALIDATION="$EXTERNAL_US_MICROSTRUCTURE_RUN_VALIDATION"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_VALIDATION_END" ] && US_MICROSTRUCTURE_VALIDATION_END="$EXTERNAL_US_MICROSTRUCTURE_VALIDATION_END"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_POST_REPORT_VALIDATION" ] && US_MICROSTRUCTURE_POST_REPORT_VALIDATION="$EXTERNAL_US_MICROSTRUCTURE_POST_REPORT_VALIDATION"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_UPDATE_PRICES" ] && US_MICROSTRUCTURE_UPDATE_PRICES="$EXTERNAL_US_MICROSTRUCTURE_UPDATE_PRICES"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_REPAIR_UPLOADS" ] && US_MICROSTRUCTURE_REPAIR_UPLOADS="$EXTERNAL_US_MICROSTRUCTURE_REPAIR_UPLOADS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_RUN_READINESS" ] && US_MICROSTRUCTURE_RUN_READINESS="$EXTERNAL_US_MICROSTRUCTURE_RUN_READINESS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY" ] && US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY="$EXTERNAL_US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_PRICE_CSV" ] && US_MICROSTRUCTURE_PRICE_CSV="$EXTERNAL_US_MICROSTRUCTURE_PRICE_CSV"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS" ] && US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS="$EXTERNAL_US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS"
[ -n "$EXTERNAL_QLIB_DATA_DIR" ] && QLIB_DATA_DIR="$EXTERNAL_QLIB_DATA_DIR"

DATA_DIR="${DATA_DIR:-$HOME/quantpilot_data}"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_DIR/.venv/bin/python}"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR:-$DATA_DIR/us_microstructure}"
US_MICROSTRUCTURE_DATE="${US_MICROSTRUCTURE_DATE:-}"
US_MICROSTRUCTURE_REPORT_SYMBOLS="${US_MICROSTRUCTURE_REPORT_SYMBOLS:-}"
US_MICROSTRUCTURE_NAS_HOST="${US_MICROSTRUCTURE_NAS_HOST:-nas}"
US_MICROSTRUCTURE_NAS_DIR="${US_MICROSTRUCTURE_NAS_DIR:-/volume1/docker/quantpilot/us_microstructure}"
US_MICROSTRUCTURE_SEND_EMAIL="${US_MICROSTRUCTURE_SEND_EMAIL:-false}"
US_MICROSTRUCTURE_RUN_VALIDATION="${US_MICROSTRUCTURE_RUN_VALIDATION:-true}"
US_MICROSTRUCTURE_VALIDATION_END="${US_MICROSTRUCTURE_VALIDATION_END:-}"
US_MICROSTRUCTURE_POST_REPORT_VALIDATION="${US_MICROSTRUCTURE_POST_REPORT_VALIDATION:-true}"
US_MICROSTRUCTURE_UPDATE_PRICES="${US_MICROSTRUCTURE_UPDATE_PRICES:-true}"
US_MICROSTRUCTURE_REPAIR_UPLOADS="${US_MICROSTRUCTURE_REPAIR_UPLOADS:-true}"
US_MICROSTRUCTURE_RUN_READINESS="${US_MICROSTRUCTURE_RUN_READINESS:-true}"
US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY="${US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY:-true}"
US_MICROSTRUCTURE_PRICE_CSV="${US_MICROSTRUCTURE_PRICE_CSV:-}"
US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS="${US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS:-45}"
QLIB_DATA_DIR="${QLIB_DATA_DIR:-$DATA_DIR/qlib_data}"
LOCK_DIR="${LOCK_DIR:-$PROJECT_DIR/logs/us_microstructure_report.lock}"

if [ -z "$US_MICROSTRUCTURE_DATE" ]; then
    US_MICROSTRUCTURE_DATE="$(PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.us_microstructure_dates default-report-date --base-dir "$US_MICROSTRUCTURE_DIR")"
fi
if [ -z "$US_MICROSTRUCTURE_VALIDATION_END" ]; then
    US_MICROSTRUCTURE_VALIDATION_END="$(PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.us_microstructure_dates validation-end-date --report-date "$US_MICROSTRUCTURE_DATE")"
fi

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "run_us_microstructure_report: skip (lock exists: $LOCK_DIR)"
    exit 0
fi
trap 'rmdir "$LOCK_DIR"' EXIT

run_validation() {
    local validation_end="$1"
    local validation_args=(
        --base-dir "$US_MICROSTRUCTURE_DIR"
        --qlib-dir "$QLIB_DATA_DIR"
        --end-date "$validation_end"
        --nas-host "$US_MICROSTRUCTURE_NAS_HOST"
        --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
    )
    if [ -n "$US_MICROSTRUCTURE_PRICE_CSV" ]; then
        validation_args+=(--price-csv "$US_MICROSTRUCTURE_PRICE_CSV")
    fi
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" QLIB_DATA_DIR="$QLIB_DATA_DIR" "$PYTHON_BIN" -m scripts.validate_us_microstructure_flow "${validation_args[@]}"
}

report_args=(
    --date "$US_MICROSTRUCTURE_DATE"
    --base-dir "$US_MICROSTRUCTURE_DIR"
    --nas-host "$US_MICROSTRUCTURE_NAS_HOST"
    --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
)

if [ -n "$US_MICROSTRUCTURE_REPORT_SYMBOLS" ]; then
    report_args+=(--symbols "$US_MICROSTRUCTURE_REPORT_SYMBOLS")
fi

delivery_report_args=("${report_args[@]}")
if [ "$US_MICROSTRUCTURE_SEND_EMAIL" = "true" ]; then
    delivery_report_args+=(--send-email)
fi

log "run_us_microstructure_report: start date=$US_MICROSTRUCTURE_DATE"
if [ "$US_MICROSTRUCTURE_UPDATE_PRICES" = "true" ]; then
    price_args=(
        --base-dir "$US_MICROSTRUCTURE_DIR"
        --end-date "$US_MICROSTRUCTURE_DATE"
        --lookback-days "$US_MICROSTRUCTURE_PRICE_LOOKBACK_DAYS"
        --nas-host "$US_MICROSTRUCTURE_NAS_HOST"
        --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
    )
    if [ -n "$US_MICROSTRUCTURE_REPORT_SYMBOLS" ]; then
        price_args+=(--symbols "$US_MICROSTRUCTURE_REPORT_SYMBOLS")
    fi
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.update_us_microstructure_prices "${price_args[@]}"
    if [ -z "$US_MICROSTRUCTURE_PRICE_CSV" ]; then
        US_MICROSTRUCTURE_PRICE_CSV="$US_MICROSTRUCTURE_DIR/validation/prices/us_daily_prices.csv"
    fi
fi
if [ "$US_MICROSTRUCTURE_REPAIR_UPLOADS" = "true" ]; then
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.repair_us_microstructure_nas_uploads \
        --base-dir "$US_MICROSTRUCTURE_DIR" \
        --date "$US_MICROSTRUCTURE_DATE" \
        --nas-host "$US_MICROSTRUCTURE_NAS_HOST" \
        --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
fi
if [ "$US_MICROSTRUCTURE_RUN_VALIDATION" = "true" ]; then
    log "run_us_microstructure_report: validation end=$US_MICROSTRUCTURE_VALIDATION_END"
    run_validation "$US_MICROSTRUCTURE_VALIDATION_END"
fi
if [ "$US_MICROSTRUCTURE_RUN_INTRADAY_REPLAY" = "true" ]; then
    replay_args=(
        --base-dir "$US_MICROSTRUCTURE_DIR"
        --date "$US_MICROSTRUCTURE_DATE"
        --rebuild-features
        --nas-host "$US_MICROSTRUCTURE_NAS_HOST"
        --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
    )
    if [ -n "$US_MICROSTRUCTURE_REPORT_SYMBOLS" ]; then
        replay_args+=(--symbols "$US_MICROSTRUCTURE_REPORT_SYMBOLS")
    fi
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.replay_us_microstructure_intraday "${replay_args[@]}"
fi
report_exit=0
if [ "$US_MICROSTRUCTURE_RUN_VALIDATION" = "true" ] && [ "$US_MICROSTRUCTURE_POST_REPORT_VALIDATION" = "true" ]; then
    log "run_us_microstructure_report: stage report before same-day validation"
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.report_us_microstructure_flow "${report_args[@]}" || report_exit=$?
    if [ "$report_exit" -eq 0 ]; then
        log "run_us_microstructure_report: post-report validation end=$US_MICROSTRUCTURE_DATE"
        run_validation "$US_MICROSTRUCTURE_DATE" || report_exit=$?
    fi
    if [ "$report_exit" -eq 0 ]; then
        log "run_us_microstructure_report: final report"
        PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.report_us_microstructure_flow "${delivery_report_args[@]}" || report_exit=$?
    fi
else
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.report_us_microstructure_flow "${delivery_report_args[@]}" || report_exit=$?
fi
if [ "$US_MICROSTRUCTURE_RUN_READINESS" = "true" ]; then
    readiness_exit=0
    PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.us_microstructure_readiness \
        --base-dir "$US_MICROSTRUCTURE_DIR" \
        --date "$US_MICROSTRUCTURE_DATE" \
        --nas-host "$US_MICROSTRUCTURE_NAS_HOST" \
        --nas-dir "$US_MICROSTRUCTURE_NAS_DIR" \
        --write-json || readiness_exit=$?
    if [ "$report_exit" -ne 0 ]; then
        exit "$report_exit"
    fi
    if [ "$readiness_exit" -ne 0 ]; then
        exit "$readiness_exit"
    fi
fi
if [ "$report_exit" -ne 0 ]; then
    exit "$report_exit"
fi
log "run_us_microstructure_report: done"
