#!/bin/bash
# QuantPilot US microstructure major-flow report.

set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

EXTERNAL_DATA_DIR="${DATA_DIR-}"
EXTERNAL_REPORT_DELIVERY_METHOD="${REPORT_DELIVERY_METHOD-}"
EXTERNAL_REPORT_TO="${REPORT_TO-}"
EXTERNAL_REPORT_FROM="${REPORT_FROM-}"
EXTERNAL_SMTP_HOST="${SMTP_HOST-}"
EXTERNAL_SMTP_PORT="${SMTP_PORT-}"
EXTERNAL_SMTP_USER="${SMTP_USER-}"
EXTERNAL_SMTP_PASSWORD="${SMTP_PASSWORD-}"
EXTERNAL_US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_DATE="${US_MICROSTRUCTURE_DATE-}"
EXTERNAL_US_MICROSTRUCTURE_REPORT_SYMBOLS="${US_MICROSTRUCTURE_REPORT_SYMBOLS-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_HOST="${US_MICROSTRUCTURE_NAS_HOST-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_DIR="${US_MICROSTRUCTURE_NAS_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_SEND_EMAIL="${US_MICROSTRUCTURE_SEND_EMAIL-}"

if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

if [ -f "$PROJECT_DIR/reporter/.env" ]; then
    set -a
    source "$PROJECT_DIR/reporter/.env"
    set +a
fi

[ -n "$EXTERNAL_DATA_DIR" ] && DATA_DIR="$EXTERNAL_DATA_DIR"
[ -n "$EXTERNAL_REPORT_DELIVERY_METHOD" ] && REPORT_DELIVERY_METHOD="$EXTERNAL_REPORT_DELIVERY_METHOD"
[ -n "$EXTERNAL_REPORT_TO" ] && REPORT_TO="$EXTERNAL_REPORT_TO"
[ -n "$EXTERNAL_REPORT_FROM" ] && REPORT_FROM="$EXTERNAL_REPORT_FROM"
[ -n "$EXTERNAL_SMTP_HOST" ] && SMTP_HOST="$EXTERNAL_SMTP_HOST"
[ -n "$EXTERNAL_SMTP_PORT" ] && SMTP_PORT="$EXTERNAL_SMTP_PORT"
[ -n "$EXTERNAL_SMTP_USER" ] && SMTP_USER="$EXTERNAL_SMTP_USER"
[ -n "$EXTERNAL_SMTP_PASSWORD" ] && SMTP_PASSWORD="$EXTERNAL_SMTP_PASSWORD"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_DIR" ] && US_MICROSTRUCTURE_DIR="$EXTERNAL_US_MICROSTRUCTURE_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_DATE" ] && US_MICROSTRUCTURE_DATE="$EXTERNAL_US_MICROSTRUCTURE_DATE"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_REPORT_SYMBOLS" ] && US_MICROSTRUCTURE_REPORT_SYMBOLS="$EXTERNAL_US_MICROSTRUCTURE_REPORT_SYMBOLS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_HOST" ] && US_MICROSTRUCTURE_NAS_HOST="$EXTERNAL_US_MICROSTRUCTURE_NAS_HOST"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_DIR" ] && US_MICROSTRUCTURE_NAS_DIR="$EXTERNAL_US_MICROSTRUCTURE_NAS_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_SEND_EMAIL" ] && US_MICROSTRUCTURE_SEND_EMAIL="$EXTERNAL_US_MICROSTRUCTURE_SEND_EMAIL"

DATA_DIR="${DATA_DIR:-$HOME/quantpilot_data}"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_DIR/.venv/bin/python}"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR:-$DATA_DIR/us_microstructure}"
US_MICROSTRUCTURE_DATE="${US_MICROSTRUCTURE_DATE:-$(date '+%Y-%m-%d')}"
US_MICROSTRUCTURE_REPORT_SYMBOLS="${US_MICROSTRUCTURE_REPORT_SYMBOLS:-}"
US_MICROSTRUCTURE_NAS_HOST="${US_MICROSTRUCTURE_NAS_HOST:-nas}"
US_MICROSTRUCTURE_NAS_DIR="${US_MICROSTRUCTURE_NAS_DIR:-/volume1/docker/quantpilot/us_microstructure}"
US_MICROSTRUCTURE_SEND_EMAIL="${US_MICROSTRUCTURE_SEND_EMAIL:-false}"
LOCK_DIR="${LOCK_DIR:-$PROJECT_DIR/logs/us_microstructure_report.lock}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "run_us_microstructure_report: skip (lock exists: $LOCK_DIR)"
    exit 0
fi
trap 'rmdir "$LOCK_DIR"' EXIT

args=(
    --date "$US_MICROSTRUCTURE_DATE"
    --base-dir "$US_MICROSTRUCTURE_DIR"
    --nas-host "$US_MICROSTRUCTURE_NAS_HOST"
    --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
)

if [ -n "$US_MICROSTRUCTURE_REPORT_SYMBOLS" ]; then
    args+=(--symbols "$US_MICROSTRUCTURE_REPORT_SYMBOLS")
fi

if [ "$US_MICROSTRUCTURE_SEND_EMAIL" = "true" ]; then
    args+=(--send-email)
fi

log "run_us_microstructure_report: start date=$US_MICROSTRUCTURE_DATE"
PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.report_us_microstructure_flow "${args[@]}"
log "run_us_microstructure_report: done"
