#!/bin/bash
# QuantPilot US microstructure live collector.

set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

EXTERNAL_DATA_DIR="${DATA_DIR-}"
EXTERNAL_FUTU_HOST="${FUTU_HOST-}"
EXTERNAL_FUTU_PORT="${FUTU_PORT-}"
EXTERNAL_FUTU_RSA_KEY="${FUTU_RSA_KEY-}"
EXTERNAL_US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_SYMBOLS="${US_MICROSTRUCTURE_SYMBOLS-}"
EXTERNAL_US_MICROSTRUCTURE_UNIVERSE_FILE="${US_MICROSTRUCTURE_UNIVERSE_FILE-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_HOST="${US_MICROSTRUCTURE_NAS_HOST-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_DIR="${US_MICROSTRUCTURE_NAS_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS="${US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS-}"
EXTERNAL_US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS="${US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS-}"
EXTERNAL_US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS="${US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS-}"
EXTERNAL_US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS="${US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS-}"
EXTERNAL_US_MICROSTRUCTURE_BATCH_SECONDS="${US_MICROSTRUCTURE_BATCH_SECONDS-}"
EXTERNAL_US_MICROSTRUCTURE_BOOK_LEVELS="${US_MICROSTRUCTURE_BOOK_LEVELS-}"
EXTERNAL_US_MICROSTRUCTURE_NO_NAS_SYNC="${US_MICROSTRUCTURE_NO_NAS_SYNC-}"

if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

[ -n "$EXTERNAL_DATA_DIR" ] && DATA_DIR="$EXTERNAL_DATA_DIR"
[ -n "$EXTERNAL_FUTU_HOST" ] && FUTU_HOST="$EXTERNAL_FUTU_HOST"
[ -n "$EXTERNAL_FUTU_PORT" ] && FUTU_PORT="$EXTERNAL_FUTU_PORT"
[ -n "$EXTERNAL_FUTU_RSA_KEY" ] && FUTU_RSA_KEY="$EXTERNAL_FUTU_RSA_KEY"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_DIR" ] && US_MICROSTRUCTURE_DIR="$EXTERNAL_US_MICROSTRUCTURE_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_SYMBOLS" ] && US_MICROSTRUCTURE_SYMBOLS="$EXTERNAL_US_MICROSTRUCTURE_SYMBOLS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_UNIVERSE_FILE" ] && US_MICROSTRUCTURE_UNIVERSE_FILE="$EXTERNAL_US_MICROSTRUCTURE_UNIVERSE_FILE"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_HOST" ] && US_MICROSTRUCTURE_NAS_HOST="$EXTERNAL_US_MICROSTRUCTURE_NAS_HOST"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_DIR" ] && US_MICROSTRUCTURE_NAS_DIR="$EXTERNAL_US_MICROSTRUCTURE_NAS_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS" ] && US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS="$EXTERNAL_US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS" ] && US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS="$EXTERNAL_US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS" ] && US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS="$EXTERNAL_US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS" ] && US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS="$EXTERNAL_US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_BATCH_SECONDS" ] && US_MICROSTRUCTURE_BATCH_SECONDS="$EXTERNAL_US_MICROSTRUCTURE_BATCH_SECONDS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_BOOK_LEVELS" ] && US_MICROSTRUCTURE_BOOK_LEVELS="$EXTERNAL_US_MICROSTRUCTURE_BOOK_LEVELS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NO_NAS_SYNC" ] && US_MICROSTRUCTURE_NO_NAS_SYNC="$EXTERNAL_US_MICROSTRUCTURE_NO_NAS_SYNC"

DATA_DIR="${DATA_DIR:-$HOME/quantpilot_data}"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_DIR/.venv/bin/python}"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
FUTU_HOST="${FUTU_HOST:-127.0.0.1}"
FUTU_PORT="${FUTU_PORT:-11111}"
FUTU_RSA_KEY="${FUTU_RSA_KEY:-$PROJECT_DIR/keys/futu_rsa_1024.pem}"
US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR:-$DATA_DIR/us_microstructure}"
US_MICROSTRUCTURE_SYMBOLS="${US_MICROSTRUCTURE_SYMBOLS:-}"
US_MICROSTRUCTURE_UNIVERSE_FILE="${US_MICROSTRUCTURE_UNIVERSE_FILE:-$PROJECT_DIR/config/us_microstructure_core_symbols.txt}"
US_MICROSTRUCTURE_NAS_HOST="${US_MICROSTRUCTURE_NAS_HOST:-nas}"
US_MICROSTRUCTURE_NAS_DIR="${US_MICROSTRUCTURE_NAS_DIR:-/volume1/docker/quantpilot/us_microstructure}"
US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS="${US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS:-30000}"
US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS="${US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS:-1}"
US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS="${US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS:-1}"
US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS="${US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS:-5}"
US_MICROSTRUCTURE_BATCH_SECONDS="${US_MICROSTRUCTURE_BATCH_SECONDS:-60}"
US_MICROSTRUCTURE_BOOK_LEVELS="${US_MICROSTRUCTURE_BOOK_LEVELS:-10}"
US_MICROSTRUCTURE_NO_NAS_SYNC="${US_MICROSTRUCTURE_NO_NAS_SYNC:-false}"
LOCK_DIR="${LOCK_DIR:-$PROJECT_DIR/logs/us_microstructure_collect.lock}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

mkdir -p "$PROJECT_DIR/logs" "$US_MICROSTRUCTURE_DIR"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "run_us_microstructure_collect: skip (lock exists: $LOCK_DIR)"
    exit 0
fi
trap 'rmdir "$LOCK_DIR"' EXIT

args=(
    --duration-seconds "$US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS"
    --poll-interval-seconds "$US_MICROSTRUCTURE_POLL_INTERVAL_SECONDS"
    --book-interval-seconds "$US_MICROSTRUCTURE_BOOK_INTERVAL_SECONDS"
    --quote-interval-seconds "$US_MICROSTRUCTURE_QUOTE_INTERVAL_SECONDS"
    --batch-seconds "$US_MICROSTRUCTURE_BATCH_SECONDS"
    --book-levels "$US_MICROSTRUCTURE_BOOK_LEVELS"
    --host "$FUTU_HOST"
    --port "$FUTU_PORT"
    --rsa-key "$FUTU_RSA_KEY"
    --local-dir "$US_MICROSTRUCTURE_DIR"
    --nas-host "$US_MICROSTRUCTURE_NAS_HOST"
    --nas-dir "$US_MICROSTRUCTURE_NAS_DIR"
)

if [ -n "$US_MICROSTRUCTURE_SYMBOLS" ]; then
    args+=(--symbols "$US_MICROSTRUCTURE_SYMBOLS")
elif [ -f "$US_MICROSTRUCTURE_UNIVERSE_FILE" ]; then
    args+=(--universe-file "$US_MICROSTRUCTURE_UNIVERSE_FILE")
fi

if [ "$US_MICROSTRUCTURE_NO_NAS_SYNC" = "true" ]; then
    args+=(--no-nas-sync)
fi

log "run_us_microstructure_collect: start duration=${US_MICROSTRUCTURE_COLLECT_DURATION_SECONDS}s"
PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.collect_us_microstructure "${args[@]}"
log "run_us_microstructure_collect: done"
