#!/bin/bash
# QuantPilot US daily pipeline
# Steps: build US universe -> deep-analysis -> write trade plan

set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

EXTERNAL_DATA_DIR="${DATA_DIR-}"
EXTERNAL_FUTU_HOST="${FUTU_HOST-}"
EXTERNAL_FUTU_PORT="${FUTU_PORT-}"
EXTERNAL_FUTU_SIM_ACC_ID="${FUTU_SIM_ACC_ID-}"
EXTERNAL_FUTU_RSA_KEY="${FUTU_RSA_KEY-}"
EXTERNAL_US_SIGNAL_DIR="${US_SIGNAL_DIR-}"
EXTERNAL_US_UNIVERSE="${US_UNIVERSE-}"
EXTERNAL_US_TARGET_CODES="${US_TARGET_CODES-}"
EXTERNAL_US_TARGET_INDEXES="${US_TARGET_INDEXES-}"
EXTERNAL_US_UNIVERSE_FILE="${US_UNIVERSE_FILE-}"
EXTERNAL_US_ANALYSIS_TOP_K="${US_ANALYSIS_TOP_K-}"
EXTERNAL_US_ANALYSIS_CONCURRENCY="${US_ANALYSIS_CONCURRENCY-}"
EXTERNAL_US_MAX_POSITIONS="${US_MAX_POSITIONS-}"
EXTERNAL_US_MIN_PRICE="${US_MIN_PRICE-}"
EXTERNAL_US_MIN_DOLLAR_VOLUME="${US_MIN_DOLLAR_VOLUME-}"
EXTERNAL_US_FUTU_CONNECT_TIMEOUT_SECONDS="${US_FUTU_CONNECT_TIMEOUT_SECONDS-}"
EXTERNAL_TRADING_AGENTS_DIR="${TRADING_AGENTS_DIR-}"
EXTERNAL_TRADING_AGENTS_SCRIPT="${TRADING_AGENTS_SCRIPT-}"

if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

[ -n "$EXTERNAL_DATA_DIR" ] && DATA_DIR="$EXTERNAL_DATA_DIR"
[ -n "$EXTERNAL_FUTU_HOST" ] && FUTU_HOST="$EXTERNAL_FUTU_HOST"
[ -n "$EXTERNAL_FUTU_PORT" ] && FUTU_PORT="$EXTERNAL_FUTU_PORT"
[ -n "$EXTERNAL_FUTU_SIM_ACC_ID" ] && FUTU_SIM_ACC_ID="$EXTERNAL_FUTU_SIM_ACC_ID"
[ -n "$EXTERNAL_FUTU_RSA_KEY" ] && FUTU_RSA_KEY="$EXTERNAL_FUTU_RSA_KEY"
[ -n "$EXTERNAL_US_SIGNAL_DIR" ] && US_SIGNAL_DIR="$EXTERNAL_US_SIGNAL_DIR"
[ -n "$EXTERNAL_US_UNIVERSE" ] && US_UNIVERSE="$EXTERNAL_US_UNIVERSE"
[ -n "$EXTERNAL_US_TARGET_CODES" ] && US_TARGET_CODES="$EXTERNAL_US_TARGET_CODES"
[ -n "$EXTERNAL_US_TARGET_INDEXES" ] && US_TARGET_INDEXES="$EXTERNAL_US_TARGET_INDEXES"
[ -n "$EXTERNAL_US_UNIVERSE_FILE" ] && US_UNIVERSE_FILE="$EXTERNAL_US_UNIVERSE_FILE"
[ -n "$EXTERNAL_US_ANALYSIS_TOP_K" ] && US_ANALYSIS_TOP_K="$EXTERNAL_US_ANALYSIS_TOP_K"
[ -n "$EXTERNAL_US_ANALYSIS_CONCURRENCY" ] && US_ANALYSIS_CONCURRENCY="$EXTERNAL_US_ANALYSIS_CONCURRENCY"
[ -n "$EXTERNAL_US_MAX_POSITIONS" ] && US_MAX_POSITIONS="$EXTERNAL_US_MAX_POSITIONS"
[ -n "$EXTERNAL_US_MIN_PRICE" ] && US_MIN_PRICE="$EXTERNAL_US_MIN_PRICE"
[ -n "$EXTERNAL_US_MIN_DOLLAR_VOLUME" ] && US_MIN_DOLLAR_VOLUME="$EXTERNAL_US_MIN_DOLLAR_VOLUME"
[ -n "$EXTERNAL_US_FUTU_CONNECT_TIMEOUT_SECONDS" ] && US_FUTU_CONNECT_TIMEOUT_SECONDS="$EXTERNAL_US_FUTU_CONNECT_TIMEOUT_SECONDS"
[ -n "$EXTERNAL_TRADING_AGENTS_DIR" ] && TRADING_AGENTS_DIR="$EXTERNAL_TRADING_AGENTS_DIR"
[ -n "$EXTERNAL_TRADING_AGENTS_SCRIPT" ] && TRADING_AGENTS_SCRIPT="$EXTERNAL_TRADING_AGENTS_SCRIPT"

DATA_DIR="${DATA_DIR:-$HOME/quantpilot_data}"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_DIR/.venv/bin/python}"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
US_SIGNAL_DIR="${US_SIGNAL_DIR:-$DATA_DIR/signals/us}"
US_UNIVERSE="${US_UNIVERSE:-sp500}"
US_ANALYSIS_TOP_K="${US_ANALYSIS_TOP_K:-0}"
US_ANALYSIS_CONCURRENCY="${US_ANALYSIS_CONCURRENCY:-10}"
US_MAX_POSITIONS="${US_MAX_POSITIONS:-5}"
US_MIN_PRICE="${US_MIN_PRICE:-5}"
US_MIN_DOLLAR_VOLUME="${US_MIN_DOLLAR_VOLUME:-10000000}"
TRADING_AGENTS_DIR="${TRADING_AGENTS_DIR:-$HOME/.openclaw/workspace/trading-agents}"
TRADING_AGENTS_SCRIPT="${TRADING_AGENTS_SCRIPT:-$TRADING_AGENTS_DIR/run_analysis.sh}"
LOCK_DIR="${LOCK_DIR:-$PROJECT_DIR/logs/us_daily.lock}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "run_us_daily: skip (lock exists: $LOCK_DIR)"
    exit 0
fi
trap 'rmdir "$LOCK_DIR"' EXIT

log "run_us_daily: start"
source .venv/bin/activate
mkdir -p "$US_SIGNAL_DIR"

PYTHONPATH="$PYTHONPATH" \
DATA_DIR="$DATA_DIR" \
FUTU_HOST="${FUTU_HOST:-}" \
FUTU_PORT="${FUTU_PORT:-}" \
FUTU_SIM_ACC_ID="${FUTU_SIM_ACC_ID:-}" \
FUTU_RSA_KEY="${FUTU_RSA_KEY:-}" \
US_SIGNAL_DIR="$US_SIGNAL_DIR" \
US_UNIVERSE="$US_UNIVERSE" \
US_TARGET_CODES="${US_TARGET_CODES:-}" \
US_TARGET_INDEXES="${US_TARGET_INDEXES:-}" \
US_UNIVERSE_FILE="${US_UNIVERSE_FILE:-}" \
US_ANALYSIS_TOP_K="$US_ANALYSIS_TOP_K" \
US_ANALYSIS_CONCURRENCY="$US_ANALYSIS_CONCURRENCY" \
US_MAX_POSITIONS="$US_MAX_POSITIONS" \
US_MIN_PRICE="$US_MIN_PRICE" \
US_MIN_DOLLAR_VOLUME="$US_MIN_DOLLAR_VOLUME" \
US_FUTU_CONNECT_TIMEOUT_SECONDS="${US_FUTU_CONNECT_TIMEOUT_SECONDS:-}" \
TRADING_AGENTS_DIR="$TRADING_AGENTS_DIR" \
TRADING_AGENTS_SCRIPT="$TRADING_AGENTS_SCRIPT" \
"$PYTHON_BIN" -m inference.run_us_daily

log "run_us_daily: done"
