#!/bin/bash
# Prune local US microstructure raw parquet after verified NAS archival.

set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

EXTERNAL_DATA_DIR="${DATA_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_RAW_RETENTION_DAYS="${US_MICROSTRUCTURE_RAW_RETENTION_DAYS-}"
EXTERNAL_US_MICROSTRUCTURE_CLEANUP_EXECUTE="${US_MICROSTRUCTURE_CLEANUP_EXECUTE-}"
EXTERNAL_US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES="${US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES-}"
EXTERNAL_US_MICROSTRUCTURE_NAS_MOUNT_DIR="${US_MICROSTRUCTURE_NAS_MOUNT_DIR-}"
EXTERNAL_US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT="${US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT-}"
EXTERNAL_FUTU_OPEND_LOG_DIR="${FUTU_OPEND_LOG_DIR-}"
EXTERNAL_FUTU_OPEND_LOG_RETENTION_DAYS="${FUTU_OPEND_LOG_RETENTION_DAYS-}"
EXTERNAL_QUANTPILOT_LOG_DIR="${QUANTPILOT_LOG_DIR-}"
EXTERNAL_QUANTPILOT_LOG_RETENTION_DAYS="${QUANTPILOT_LOG_RETENTION_DAYS-}"
EXTERNAL_LOCAL_RUNTIME_LOG_CLEANUP_NOW="${LOCAL_RUNTIME_LOG_CLEANUP_NOW-}"

if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

[ -n "$EXTERNAL_DATA_DIR" ] && DATA_DIR="$EXTERNAL_DATA_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_DIR" ] && US_MICROSTRUCTURE_DIR="$EXTERNAL_US_MICROSTRUCTURE_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_RAW_RETENTION_DAYS" ] && US_MICROSTRUCTURE_RAW_RETENTION_DAYS="$EXTERNAL_US_MICROSTRUCTURE_RAW_RETENTION_DAYS"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_CLEANUP_EXECUTE" ] && US_MICROSTRUCTURE_CLEANUP_EXECUTE="$EXTERNAL_US_MICROSTRUCTURE_CLEANUP_EXECUTE"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES" ] && US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES="$EXTERNAL_US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_NAS_MOUNT_DIR" ] && US_MICROSTRUCTURE_NAS_MOUNT_DIR="$EXTERNAL_US_MICROSTRUCTURE_NAS_MOUNT_DIR"
[ -n "$EXTERNAL_US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT" ] && US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT="$EXTERNAL_US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT"
[ -n "$EXTERNAL_FUTU_OPEND_LOG_DIR" ] && FUTU_OPEND_LOG_DIR="$EXTERNAL_FUTU_OPEND_LOG_DIR"
[ -n "$EXTERNAL_FUTU_OPEND_LOG_RETENTION_DAYS" ] && FUTU_OPEND_LOG_RETENTION_DAYS="$EXTERNAL_FUTU_OPEND_LOG_RETENTION_DAYS"
[ -n "$EXTERNAL_QUANTPILOT_LOG_DIR" ] && QUANTPILOT_LOG_DIR="$EXTERNAL_QUANTPILOT_LOG_DIR"
[ -n "$EXTERNAL_QUANTPILOT_LOG_RETENTION_DAYS" ] && QUANTPILOT_LOG_RETENTION_DAYS="$EXTERNAL_QUANTPILOT_LOG_RETENTION_DAYS"
[ -n "$EXTERNAL_LOCAL_RUNTIME_LOG_CLEANUP_NOW" ] && LOCAL_RUNTIME_LOG_CLEANUP_NOW="$EXTERNAL_LOCAL_RUNTIME_LOG_CLEANUP_NOW"

DATA_DIR="${DATA_DIR:-$HOME/quantpilot_data}"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_DIR/.venv/bin/python}"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
US_MICROSTRUCTURE_DIR="${US_MICROSTRUCTURE_DIR:-$DATA_DIR/us_microstructure}"
US_MICROSTRUCTURE_RAW_RETENTION_DAYS="${US_MICROSTRUCTURE_RAW_RETENTION_DAYS:-7}"
US_MICROSTRUCTURE_CLEANUP_EXECUTE="${US_MICROSTRUCTURE_CLEANUP_EXECUTE:-true}"
US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT="${US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT:-false}"
FUTU_OPEND_LOG_DIR="${FUTU_OPEND_LOG_DIR:-$HOME/.com.futunn.FutuOpenD/Log}"
FUTU_OPEND_LOG_RETENTION_DAYS="${FUTU_OPEND_LOG_RETENTION_DAYS:-14}"
QUANTPILOT_LOG_DIR="${QUANTPILOT_LOG_DIR:-$PROJECT_DIR/logs}"
QUANTPILOT_LOG_RETENTION_DAYS="${QUANTPILOT_LOG_RETENTION_DAYS:-30}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] run_us_microstructure_cleanup: $*"
}

mkdir -p "$PROJECT_DIR/logs"

if [ ! -x "$PYTHON_BIN" ]; then
    PYTHON_BIN="$(command -v python3 || true)"
fi
if [ -z "$PYTHON_BIN" ]; then
    log "python not found"
    exit 2
fi

args=(
    --base-dir "$US_MICROSTRUCTURE_DIR"
    --retention-days "$US_MICROSTRUCTURE_RAW_RETENTION_DAYS"
)

if [ "$US_MICROSTRUCTURE_CLEANUP_EXECUTE" = "true" ]; then
    args+=(--execute)
fi

if [ -n "${US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES-}" ]; then
    args+=(--max-delete-bytes "$US_MICROSTRUCTURE_CLEANUP_MAX_DELETE_BYTES")
fi

if [ -n "${US_MICROSTRUCTURE_NAS_MOUNT_DIR-}" ]; then
    args+=(--nas-mount-dir "$US_MICROSTRUCTURE_NAS_MOUNT_DIR")
fi

if [ "$US_MICROSTRUCTURE_CLEANUP_VERIFY_NAS_MOUNT" = "true" ]; then
    args+=(--verify-nas-mount)
fi

log "start retention_days=$US_MICROSTRUCTURE_RAW_RETENTION_DAYS execute=$US_MICROSTRUCTURE_CLEANUP_EXECUTE"
PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.cleanup_us_microstructure_archive "${args[@]}"

runtime_args=(
    --futu-log-dir "$FUTU_OPEND_LOG_DIR"
    --futu-retention-days "$FUTU_OPEND_LOG_RETENTION_DAYS"
    --quantpilot-log-dir "$QUANTPILOT_LOG_DIR"
    --quantpilot-retention-days "$QUANTPILOT_LOG_RETENTION_DAYS"
)

if [ "$US_MICROSTRUCTURE_CLEANUP_EXECUTE" = "true" ]; then
    runtime_args+=(--execute)
fi

if [ -n "${LOCAL_RUNTIME_LOG_CLEANUP_NOW-}" ]; then
    runtime_args+=(--now "$LOCAL_RUNTIME_LOG_CLEANUP_NOW")
fi

log "runtime log cleanup start futu_retention_days=$FUTU_OPEND_LOG_RETENTION_DAYS quantpilot_retention_days=$QUANTPILOT_LOG_RETENTION_DAYS execute=$US_MICROSTRUCTURE_CLEANUP_EXECUTE"
PYTHONPATH="$PYTHONPATH" DATA_DIR="$DATA_DIR" "$PYTHON_BIN" -m scripts.cleanup_local_runtime_logs "${runtime_args[@]}"
log "done"
