#!/bin/bash
# QuantPilot US watchlist deep-analysis report
# Reads a user-maintained watchlist, runs deep-analysis, and emails a detailed report.

set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

EXTERNAL_DATA_DIR="${DATA_DIR-}"
EXTERNAL_REPORT_DELIVERY_METHOD="${REPORT_DELIVERY_METHOD-}"
EXTERNAL_REPORT_TO="${REPORT_TO-}"
EXTERNAL_REPORT_FROM="${REPORT_FROM-}"
EXTERNAL_SMTP_HOST="${SMTP_HOST-}"
EXTERNAL_SMTP_PORT="${SMTP_PORT-}"
EXTERNAL_SMTP_USER="${SMTP_USER-}"
EXTERNAL_SMTP_PASSWORD="${SMTP_PASSWORD-}"
EXTERNAL_US_WATCHLIST_FILE="${US_WATCHLIST_FILE-}"
EXTERNAL_US_WATCHLIST_REPORT_DIR="${US_WATCHLIST_REPORT_DIR-}"
EXTERNAL_US_WATCHLIST_CONCURRENCY="${US_WATCHLIST_CONCURRENCY-}"
EXTERNAL_US_WATCHLIST_TIMEOUT_SECONDS="${US_WATCHLIST_TIMEOUT_SECONDS-}"
EXTERNAL_US_WATCHLIST_RETRY_COUNT="${US_WATCHLIST_RETRY_COUNT-}"
EXTERNAL_US_WATCHLIST_SEND_EMAIL="${US_WATCHLIST_SEND_EMAIL-}"
EXTERNAL_TRADING_AGENTS_DIR="${TRADING_AGENTS_DIR-}"
EXTERNAL_TRADING_AGENTS_SCRIPT="${TRADING_AGENTS_SCRIPT-}"

if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

if [ -f "$PROJECT_DIR/reporter/.env" ]; then
    set -a
    source "$PROJECT_DIR/reporter/.env"
    set +a
fi

[ -n "$EXTERNAL_DATA_DIR" ] && DATA_DIR="$EXTERNAL_DATA_DIR"
[ -n "$EXTERNAL_REPORT_DELIVERY_METHOD" ] && REPORT_DELIVERY_METHOD="$EXTERNAL_REPORT_DELIVERY_METHOD"
[ -n "$EXTERNAL_REPORT_TO" ] && REPORT_TO="$EXTERNAL_REPORT_TO"
[ -n "$EXTERNAL_REPORT_FROM" ] && REPORT_FROM="$EXTERNAL_REPORT_FROM"
[ -n "$EXTERNAL_SMTP_HOST" ] && SMTP_HOST="$EXTERNAL_SMTP_HOST"
[ -n "$EXTERNAL_SMTP_PORT" ] && SMTP_PORT="$EXTERNAL_SMTP_PORT"
[ -n "$EXTERNAL_SMTP_USER" ] && SMTP_USER="$EXTERNAL_SMTP_USER"
[ -n "$EXTERNAL_SMTP_PASSWORD" ] && SMTP_PASSWORD="$EXTERNAL_SMTP_PASSWORD"
[ -n "$EXTERNAL_US_WATCHLIST_FILE" ] && US_WATCHLIST_FILE="$EXTERNAL_US_WATCHLIST_FILE"
[ -n "$EXTERNAL_US_WATCHLIST_REPORT_DIR" ] && US_WATCHLIST_REPORT_DIR="$EXTERNAL_US_WATCHLIST_REPORT_DIR"
[ -n "$EXTERNAL_US_WATCHLIST_CONCURRENCY" ] && US_WATCHLIST_CONCURRENCY="$EXTERNAL_US_WATCHLIST_CONCURRENCY"
[ -n "$EXTERNAL_US_WATCHLIST_TIMEOUT_SECONDS" ] && US_WATCHLIST_TIMEOUT_SECONDS="$EXTERNAL_US_WATCHLIST_TIMEOUT_SECONDS"
[ -n "$EXTERNAL_US_WATCHLIST_RETRY_COUNT" ] && US_WATCHLIST_RETRY_COUNT="$EXTERNAL_US_WATCHLIST_RETRY_COUNT"
[ -n "$EXTERNAL_US_WATCHLIST_SEND_EMAIL" ] && US_WATCHLIST_SEND_EMAIL="$EXTERNAL_US_WATCHLIST_SEND_EMAIL"
[ -n "$EXTERNAL_TRADING_AGENTS_DIR" ] && TRADING_AGENTS_DIR="$EXTERNAL_TRADING_AGENTS_DIR"
[ -n "$EXTERNAL_TRADING_AGENTS_SCRIPT" ] && TRADING_AGENTS_SCRIPT="$EXTERNAL_TRADING_AGENTS_SCRIPT"

DATA_DIR="${DATA_DIR:-$HOME/quantpilot_data}"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_DIR/.venv/bin/python}"
PYTHONPATH="${PROJECT_DIR}${PYTHONPATH:+:$PYTHONPATH}"
US_WATCHLIST_FILE="${US_WATCHLIST_FILE:-$DATA_DIR/config/us_watchlist.json}"
US_WATCHLIST_REPORT_DIR="${US_WATCHLIST_REPORT_DIR:-$DATA_DIR/reports/us_watchlist}"
US_WATCHLIST_CONCURRENCY="${US_WATCHLIST_CONCURRENCY:-2}"
US_WATCHLIST_TIMEOUT_SECONDS="${US_WATCHLIST_TIMEOUT_SECONDS:-3600}"
US_WATCHLIST_RETRY_COUNT="${US_WATCHLIST_RETRY_COUNT:-0}"
US_WATCHLIST_SEND_EMAIL="${US_WATCHLIST_SEND_EMAIL:-true}"
TRADING_AGENTS_DIR="${TRADING_AGENTS_DIR:-$HOME/.openclaw/workspace/trading-agents}"
TRADING_AGENTS_SCRIPT="${TRADING_AGENTS_SCRIPT:-$TRADING_AGENTS_DIR/run_analysis.sh}"
REPORTER_ENV_FILE="${REPORTER_ENV_FILE:-$PROJECT_DIR/reporter/.env}"
LOCK_DIR="${LOCK_DIR:-$PROJECT_DIR/logs/us_watchlist_report.lock}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    log "run_us_watchlist_report: skip (lock exists: $LOCK_DIR)"
    exit 0
fi
trap 'rmdir "$LOCK_DIR"' EXIT

log "run_us_watchlist_report: start"
source .venv/bin/activate
mkdir -p "$US_WATCHLIST_REPORT_DIR"

PYTHONPATH="$PYTHONPATH" \
DATA_DIR="$DATA_DIR" \
REPORTER_ENV_FILE="$REPORTER_ENV_FILE" \
US_WATCHLIST_FILE="$US_WATCHLIST_FILE" \
US_WATCHLIST_REPORT_DIR="$US_WATCHLIST_REPORT_DIR" \
US_WATCHLIST_CONCURRENCY="$US_WATCHLIST_CONCURRENCY" \
US_WATCHLIST_TIMEOUT_SECONDS="$US_WATCHLIST_TIMEOUT_SECONDS" \
US_WATCHLIST_RETRY_COUNT="$US_WATCHLIST_RETRY_COUNT" \
US_WATCHLIST_SEND_EMAIL="$US_WATCHLIST_SEND_EMAIL" \
TRADING_AGENTS_DIR="$TRADING_AGENTS_DIR" \
TRADING_AGENTS_SCRIPT="$TRADING_AGENTS_SCRIPT" \
"$PYTHON_BIN" -m inference.run_us_watchlist_report

log "run_us_watchlist_report: done"
